apiVersion: v2
# Touch comment to trigger the product service chart pipeline.
name: product-service
description: A Helm chart for product-service
type: application
version: 0.1.0
appVersion: "1.0.0"
